{ lib, config, pkgs, ... }:

let
  emacsPkg = pkgs.emacs-pgtk;

  fontSize = size: toString size;

  # ── Static doomdir source ────────────────────────────────────────────
  doomConfigPrelude = ''
    ;;; Generated by Nix — do not edit.

    (defun my/setup-fonts (&optional _frame)
      "Apply font and fontset configuration. Safe to call from a frame hook."
      (when (display-graphic-p)
        (setq doom-font                (font-spec :family "JetBrainsMonoNL Nerd Font Propo" :size ${fontSize 16} :weight 'regular)
              doom-variable-pitch-font (font-spec :family "Inter"                           :size ${fontSize 16} :weight 'regular)
              doom-big-font            (font-spec :family "JetBrainsMonoNL Nerd Font Propo" :size ${fontSize 20} :weight 'regular)
              doom-symbol-font         (font-spec :family "Symbols Nerd Font"               :size ${fontSize 16})
              doom-serif-font          (font-spec :family "FreeSerif"                       :size ${fontSize 16} :weight 'regular)
              nerd-icons-font-names    '("JetBrainsMonoNFP-Regular.ttf")
              nerd-icons-font-family   "JetBrainsMonoNL Nerd Font Propo")

        (set-fontset-font t 'cyrillic (font-spec :family "DejaVu Sans Mono"))
        (set-fontset-font t '(#xe000  . #xf8ff)  (font-spec :family "Symbols Nerd Font Mono") nil 'prepend)
        (set-fontset-font t '(#xf0000 . #xfffff) (font-spec :family "Symbols Nerd Font Mono") nil 'prepend)

        (when (fboundp 'doom/reload-font)
          (doom/reload-font))))

    (if (daemonp)
        (add-hook 'server-after-make-frame-hook #'my/setup-fonts)
      (my/setup-fonts))


    ;;; =========================================================
    ;;; Edit Freely

    (setq lsp-use-plists t)
  '';

  doomDir = pkgs.runCommand "doomdir" { } ''
    mkdir -p $out
    cp ${./doom/init.el}     $out/init.el
    cp ${./doom/custom.el}   $out/custom.el
    cp ${./doom/packages.el} $out/packages.el

    # Concatenate the generated prelude with the user-maintained config.
    cat > $out/config.el <<'EOF'
    ${doomConfigPrelude}
    EOF
    cat ${./doom/config.el} >> $out/config.el
  '';

  # ── Runtime dependencies for Doom modules ─────────────────────────────
  emacs-deps = with pkgs; [
    # core
    git fd ripgrep enchant hunspellDicts.en_US hunspellDicts.ru_RU
    cmigemo shellcheck shfmt poppler-utils vips gcc pkg-config

    # build
    gnumake cmake glslang sqlite nodejs js-beautify
    pipenv poetry ty clang-tools libxml2
    python3Packages.python dockfmt
    python3Packages.pytest python3Packages.pyflakes
    python3Packages.uv python3Packages.isort

    # formatting / linting
    nixfmt html-tidy stylelint

    # documentation
    graphviz multimarkdown
    (texlive.combine {
      inherit (pkgs.texlive) scheme-medium gost biblatex-gost;
    })

    # GUI helpers
    maim

    # language servers
    cmake-language-server nil

    # fonts
    emacs-all-the-icons-fonts
    nerd-fonts.symbols-only nerd-fonts.jetbrains-mono
    nerd-fonts.iosevka nerd-fonts.lilex
    inter
  ];
in
lib.mkIf config.my.editors.emacs.enable {

  # ── Unstraightened ────────────────────────────────────────────────────
  programs.doom-emacs = {
    enable        = true;
    inherit doomDir;
    emacs         = emacsPkg;

    doomLocalDir  = "${config.xdg.dataHome}/nix-doom";

    # If you don't want the per-profile subdirs ("~/.cache/doom/nix" etc.)
    # and prefer the traditional Doom paths, uncomment:
    # profileName = "";

    extraPackages = epkgs: [
      epkgs.treesit-grammars.with-all-grammars
    ];

    provideEmacs = true;
  };

  # ── Daemon ────────────────────────────────────────────────────────────
  services.emacs = {
    enable                  = true;
    client.enable           = true;
    socketActivation.enable = true;
    startWithUserSession    = false;
  };

  # ── Environment ───────────────────────────────────────────────────────
  home.sessionVariables = {
    EDITOR  = "emacsclient --alternate-editor=emacs";
    VISUAL  = "emacsclient --alternate-editor=emacs";
    DICPATH = "${pkgs.hunspellDicts.en_US}/share/hunspell:${pkgs.hunspellDicts.ru_RU}/share/hunspell";
  };

  home.packages = emacs-deps;
}
