$mod = SUPER 

# Application Launchers
bind = $mod, R,     exec, dms ipc call spotlight toggle
bind = $mod, V,     exec, dms ipc call clipboard toggle
bind = $mod, comma, exec, dms ipc call settings focusOrToggle
bind = $mod, Y,     exec, dms ipc call dankdash wallpaper
# bind = $mod, M, exec, dms ipc call processlist focusOrToggle
# bind = $mod, N, exec, dms ipc call notifications toggle
# bind = $mod, TAB, exec, dms ipc call hypr toggleOverview

# Security
# bind = $mod, Z, exec, dms ipc call lock lock

# Audio Controls
bindel = , XF86AudioRaiseVolume, exec, dms ipc call audio increment 3
bindel = , XF86AudioLowerVolume, exec, dms ipc call audio decrement 3
bindl  = , XF86AudioMute,        exec, dms ipc call audio mute

# Brightness Controls
bindel = , XF86MonBrightnessUp,   exec, dms ipc call brightness increment 5 backlight:amdgpu_bl1
bindel = , XF86MonBrightnessDown, exec, dms ipc call brightness decrement 5 backlight:amdgpu_bl1
