# Launcher
bind   = Super, R,           global, caelestia:launcher
bindin = Super, catchall,   global, caelestia:launcherInterrupt
bindin = Super, mouse:272,  global, caelestia:launcherInterrupt
bindin = Super, mouse:273,  global, caelestia:launcherInterrupt
bindin = Super, mouse:274,  global, caelestia:launcherInterrupt
bindin = Super, mouse:275,  global, caelestia:launcherInterrupt
bindin = Super, mouse:276,  global, caelestia:launcherInterrupt
bindin = Super, mouse:277,  global, caelestia:launcherInterrupt
bindin = Super, mouse_up,   global, caelestia:launcherInterrupt
bindin = Super, mouse_down, global, caelestia:launcherInterrupt

# Misc
bind  = Ctrl+Alt, Delete, global, caelestia:session
bindl = Ctrl+Alt, C, global, caelestia:clearNotifs
# bind = Super, K, global, caelestia:showall
bind = Super, X, global, caelestia:lock
bind = SUPER, V, exec, kitty -o background_opacity=0.7 -o font_size=13 --class clipse -e zsh -c 'clipse'


# Restore lock
bindl = Super+Alt, L, exec, caelestia shell -d

# Brightness
bindel = , XF86MonBrightnessUp,   global, caelestia:brightnessUp
bindel = , XF86MonBrightnessDown, global, caelestia:brightnessDown
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-


# Media
bindl = , XF86AudioPlay,  global, caelestia:mediaToggle
bindl = , XF86AudioPause, global, caelestia:mediaToggle
bindl = , XF86AudioNext,  global, caelestia:mediaNext
bindl = , XF86AudioPrev,  global, caelestia:mediaPrev
bindl = , XF86AudioStop,  global, caelestia:mediaStop
